# Generated by Django 3.2.5 on 2021-07-07 04:15

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteristica', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaCultura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path),
        ),
        migrations.CreateModel(
            name='EntradasCultura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path)),
                ('video', models.URLField(blank=True, max_length=1500, null=True)),
                ('description', models.TextField(null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categoriacultura')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='caracteristicas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.caracteristica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='presentaciones',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.presentacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='subcategoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.subcategoria'),
            preserve_default=False,
        ),
    ]
